### ISSUE TITLE
Possibility of porting to Linux/macOS natively?

### ISSUE THREAD

**Issue by shreyanshk** [neatodev/AsylumLauncher#3]
First of all, thank you for the awesome work you've accomplished in this repository. I have a (hopefully quick) question for you.

Is this Advanced Launcher capable of fully replacing the old launcher shipped with the game? If yes, perhaps we can figure out a way to natively port this awesome game to Linux and macOS. From the looks of this repository, it seems that this launcher has also ported some program logic that shipped with the original launcher... But, I'm not too sure. So I thought I'd write to you and ask.

I have a background in Software Engineering. So, I have some ideas. One of those is that maybe we could cross-compile this launcher for Linux and/or macOS and copy the assets from the original game (and/or other mods). As for the dependency on dotnet, Mono is a native implementation of dotnet that is available on Linux and macOS.

Feel free to share your thoughts. Thanks.

**Comment by neatodev** [comment]
I don't see the need for a linux native version. The launcher runs perfectly fine through Wine, which the game uses anyway, since there is no native linux port of the game. Mono handles all of the dotnet mappings fine when you run it through Wine.

What is the benefit of a native linux port of this program when the game itself doesn't have one?

**Comment by shreyanshk** [comment]
I think that main benefit of the native port would be that we could bring this game to year 2024 (and beyond). That would mean significantly better gaming experience in terms of stability, frame rate etc and also make it easier for today's gamers to approach and run this game.

Matter of fact, I only discovered this repository because of chain of problems every step of the way trying to run games on my computer. I started with trying to run other unrelated games with Apple's GPTK and Whisky. I then had to experiment with these tools to try to get good experience on many games and still there were many stability and framerate issues. For example, for me, this Batman game in its unmodded state has terrible stability and framerate issues under Whisky. Then I tried to mod this game with this "advanced launcher" but it won't run for me under Whisky. Gives me a blank screen. I tried installing the fonts mentioned in the readme but no dice.

So, I thought, maybe I could try to skip all these tools altogether and just run the game natively.

**Comment by shreyanshk** [comment]
I don't know about that. Anyway, I am starting to think that perhaps it isn't the best time to make such an effort.

Perhaps you can help me run the game under Whisky on macOS?
So, I installed the game from steam (running under Whisky with bottle configured to Win 10, sync set to none, retina mode enabled, dxvk disabled) and then replaced the BmLauncher file with the latest standalone launcher you have made available over nexusmods.com . I get no window output even thought steam shows the game is running and I waited for over 2 minutes.

Here are some logs from the launcher.

```
2024-12-04 19:39:51.2780|INFO|AsylumLauncher.Program|InitializeProgram - Starting logs at 19:39:51 on Wednesday, 4 December 2024.
2024-12-04 19:39:51.3129|INFO|AsylumLauncher.Program|InitializeProgram - Current application version: 2.0.0.3
2024-12-04 19:39:51.3141|INFO|AsylumLauncher.Program|InitializeProgram - Elevated Privileges: True
2024-12-04 19:39:51.4798|INFO|AsylumLauncher.Program|InitFonts - Necessary fonts installed.
2024-12-04 19:39:51.8428|ERROR|AsylumLauncher.NvidiaHandler|Constructor - Unexpected critical error during NVAPI initialization: System.DllNotFoundException: Dll was not found.
   at NvAPIWrapper.Native.Helpers.DelegateFactory.NvAPI_QueryInterface(UInt32 interfaceId)
   at NvAPIWrapper.Native.Helpers.DelegateFactory.GetDelegate[T]()
   at NvAPIWrapper.Native.GeneralApi.Initialize()
   at NvAPIWrapper.NVIDIA.Initialize()
   at AsylumLauncher.NvidiaHandler..ctor()
2024-12-04 19:39:51.8921|INFO|AsylumLauncher.FileHandler|Constructor - Successfully initialized FileHandler.
2024-12-04 19:39:51.9499|INFO|AsylumLauncher.IniHandler|Constructor - Successfully initialized IniHandler.
2024-12-04 19:39:51.9506|INFO|AsylumLauncher.InputHandler|Constructor - Successfully initialized InputHandler.
2024-12-04 19:39:51.9506|INFO|AsylumLauncher.SystemHandler|Constructor - Successfully initialized SystemHandler.
```

**Comment by neatodev** [comment]
I have no knowledge of Whisky or macOS.
The launcher seems to crash when it tries to read your system info (cpu and gpu). Shouldn't happen, because there are fallback methods in place. I know that the launcher works with Wine. Maybe try that.

**Comment by shreyanshk** [comment]
Weird. Whisky is just a GUI wrapper for wine (currently version 7.7) on macOS. Though, Whisky developers indeed do apply some minor patches to their version of wine to make it more compatible with macOS... but those patches are not expected to have any effect on the APIs exposed to applications.

Anyway, I thank you for your time and I'll write to the Whisky developers to see if they have any ideas.
